#!/usr/bin/env python3
"""
Generate a traceability map from frontmatter links across all artifacts.

Usage:
    python scripts/generate-traceability.py [--path PATH] [--output PATH]

Requires: pip install pyyaml
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: Install dependencies first: pip install pyyaml")
    sys.exit(1)

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")

# Fields that represent upstream or downstream links
LINK_FIELDS = [
    "source_docs", "related_adrs", "depends_on", "blocks",
    "implemented_by", "verified_by", "related_requirements",
    "implements", "verifies", "affects", "persona",
]


def extract_frontmatter(filepath: Path) -> dict | None:
    text = filepath.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None


def extract_links(value) -> list[str]:
    """Extract artifact IDs from frontmatter values (handles strings, lists)."""
    links = []
    if isinstance(value, str):
        for m in WIKILINK_RE.finditer(value):
            links.append(m.group(1))
        if not links and value.strip():
            links.append(value.strip())
    elif isinstance(value, list):
        for item in value:
            links.extend(extract_links(item))
    return links


def build_graph(root: Path) -> dict:
    """Build a directed graph: artifact_id -> { field_name: [linked_ids] }."""
    graph = {}
    for md_file in sorted(root.rglob("*.md")):
        if "templates" in md_file.parts:
            continue
        fm = extract_frontmatter(md_file)
        if fm is None or "id" not in fm:
            continue

        artifact_id = fm["id"]
        graph[artifact_id] = {"_title": fm.get("title", ""), "_status": fm.get("status", "")}

        for field in LINK_FIELDS:
            if field in fm and fm[field]:
                linked = extract_links(fm[field])
                if linked:
                    graph[artifact_id][field] = linked

    return graph


def generate_map(graph: dict) -> str:
    lines = [
        "---",
        "id: META-TRACEABILITY",
        "title: Auto-Generated Traceability Map",
        f"updated: {__import__('datetime').date.today().isoformat()}",
        "---",
        "",
        "# Traceability Map",
        "",
        "> This file is auto-generated by `scripts/generate-traceability.py`.",
        "> Do not edit manually. Re-run the script to update.",
        "",
    ]

    # Group by prefix
    prefixes = {}
    for aid in sorted(graph.keys()):
        prefix = aid.split("-")[0]
        prefixes.setdefault(prefix, []).append(aid)

    for prefix in ["VISION", "PERSONA", "JOURNEY", "ASSUM", "EPIC", "US", "FR", "NFR", "CON", "UC", "ADR", "CONTRACT", "DM", "TASK", "RISK", "REL", "TEST", "CR"]:
        if prefix not in prefixes:
            continue
        lines.append(f"## {prefix}")
        lines.append("")
        for aid in prefixes[prefix]:
            info = graph[aid]
            title = info.get("_title", "")
            status = info.get("_status", "")
            lines.append(f"### [[{aid}]] — {title}")
            lines.append(f"Status: `{status}`")
            lines.append("")
            for field in LINK_FIELDS:
                if field in info:
                    linked = ", ".join(f"[[{x}]]" for x in info[field])
                    lines.append(f"- **{field}**: {linked}")
            lines.append("")

    # Orphan check
    all_ids = set(graph.keys())
    all_referenced = set()
    for aid, info in graph.items():
        for field in LINK_FIELDS:
            if field in info:
                all_referenced.update(info[field])

    orphans = all_ids - all_referenced - {aid for aid in all_ids if aid.startswith("VISION") or aid.startswith("META-") or aid.startswith("GLOSS-") or aid.startswith("CODEMAP-")}
    if orphans:
        lines.append("## Orphan Artifacts")
        lines.append("")
        lines.append("These artifacts are not referenced by any other artifact:")
        lines.append("")
        for oid in sorted(orphans):
            lines.append(f"- [[{oid}]] — {graph[oid].get('_title', '')}")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate traceability map")
    parser.add_argument("--path", default=".", help="Root of requirements vault")
    parser.add_argument("--output", default=None, help="Output file (default: 05-quality/traceability/TRACEABILITY-MAP.md)")
    args = parser.parse_args()

    root = Path(args.path)
    graph = build_graph(root)

    output_path = Path(args.output) if args.output else root / "05-quality" / "traceability" / "TRACEABILITY-MAP.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_map(graph)
    output_path.write_text(content, encoding="utf-8")
    print(f"✓ Traceability map generated: {output_path}")
    print(f"  Artifacts found: {len(graph)}")


if __name__ == "__main__":
    main()
